## Desafio 5: Forbes

In [1]:
from pydataset import data
import pandas as pd

In [2]:
# Verifico o se o df está em ordem
forbes = data('Forbes2000')
forbes.head()

,rank,name,country,category,sales,profits,assets,marketvalue
1,1,Citigroup,United States,Banking,94.71,17.85,1264.03,255.30
2,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54
3,3,American Intl Group,United States,Insurance,76.66,6.46,647.66,194.87
4,4,ExxonMobil,United States,Oil & gas operations,222.88,20.96,166.99,277.02
5,5,BP,United Kingdom,Oil & gas operations,232.57,10.27,177.57,173.54

In [3]:
#1. Qual a empresa mais valiosa da lista da Forbes 2000?

# -> 1°. Conferi o valor mais alto com .max()
# -> 2°. Criei uma variável para armazenar o df organizado por 'marketvalue' de forma decrescente. Então, com o head() selecionei só a 1° empresa, a mais valiosa.

#forbes['marketvalue'].max()
mais_valiosa = forbes.sort_values('marketvalue', ascending = False).head(1)
mais_valiosa

,rank,name,country,category,sales,profits,assets,marketvalue
2,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54

In [4]:
# 2. Construa uma tabela com as TOP 10 empresas mais lucrativas da lista.

# -> 1°. Para obter os maiores valores utilizei a função nlargest, assim atravéz da coluna 'profits' os valores são verificdos e armazenados na variável.

top_10 = forbes.nlargest(10, 'profits')
top_10

,rank,name,country,category,sales,profits,assets,marketvalue
4,4,ExxonMobil,United States,Oil & gas operations,222.88,20.96,166.99,277.02
1,1,Citigroup,United States,Banking,94.71,17.85,1264.03,255.30
2,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54
6,6,Bank of America,United States,Banking,49.01,10.81,736.45,117.55
5,5,BP,United Kingdom,Oil & gas operations,232.57,10.27,177.57,173.54
20,20,Freddie Mac,United States,Diversified financials,46.26,10.09,752.25,44.25
22,22,Altria Group,United States,Food drink & tobacco,60.70,9.20,96.18,111.02
10,10,Wal-Mart Stores,United States,Retailing,256.33,9.05,104.91,243.74
31,31,Microsoft,United States,Software & services,34.27,8.88,85.94,287.02
17,17,Total,France,Oil & gas operations,131.64,8.84,87.84,116.64

In [5]:
# 3. Qual a média de valores de empresa das cinco categorias mais valiosas?

# -> 1°. Crio uma variável agrupando os dados por 'category', desta forma encontro a soma do valor de mercado das 5 categorias.
# -> 2°. Com o atributo `.index` isolei os nomes de cada categoria já filtrada no passo anterior.
# -> 3°. A variável forbes_filtrado armazena somente os dados das empresas pertencentes às 5 categorias isoladas.
# -> 4°. Como em forbes_filtrado o nome das empresas não se repentem, para tirar a média de valores de empresas usei a função .mean().

forbes_cat = forbes.groupby('category')['marketvalue'].sum().nlargest(5)
# forbes_cat

indice_cat = forbes_cat.index
# indice_cat

forbes_filtrado = forbes[forbes['category'].isin(indice_cat)]
# forbes_filtrado

media_geral_empresas = forbes_filtrado['marketvalue'].mean().round(2)

print(f'A média de valores de empresa das cinco categorias mais valiosas de Forbes2000 é: {media_geral_empresas}')

A média de valores de empresa das cinco categorias mais valiosas de Forbes2000 é: 14.57